name: CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

env:
  FORCE_COLOR: 2
  NODE_COV: 16 # The Node.js version to run coveralls on

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 10
          - 12
          - 14
          - 16

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node }}'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run Jest
        run: npm run test:jest
        if: matrix.node != env.NODE_COV

      - name: Run Jest with coverage
        run: npm run test:jest:cov
        if: matrix.node == env.NODE_COV

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == env.NODE_COV
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
