name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE }}'
          cache: 'npm'
      - run: npm ci
      - name: Build docs
        run: npm run build:docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          cname: cheerio.js.org
